config/routes.rb
OnTheIslands::Application.routes.draw do

  
  resource :sessions, only: :destroy
  match '/auth/:provider/callback', to: 'sessions#create'
  match '/auth/failure', to: 'sessions#failure'
  
  root to: 'home#index'
end

app/models/authentication.rb
class Authentication
  PROVIDERS = { google: 'Google', facebook: 'Facebook', open_id: 'OpenID' }
  
  include Mongoid::Document
  # TODO: include Mongoid::Timestamps::Created
  
  field :provider
  field :uid
  field :used_at, :type => Time
  
  embedded_in :user, :inverse_of => :authentications
  
  validates_presence_of   :uid, :provider
  validates_uniqueness_of :uid, :scope => :provider
  
  def self.from_hash(hash)
    attrs = { provider: hash['provider'], uid: hash['uid'] }
    user = User.where('authentications.provider' => hash['provider'],
                      'authentications.uid' => hash['uid']).first
    user ? user.authentications.where(attrs).first : self.new(attrs)
  end
  
  def self.auth_by_hash(hash)
    auth = self.from_hash(hash)
    auth.used_at = Time.now
    auth
  end
  
  def provider_name
    PROVIDERS[provider.to_sym] || provider
  end
end

app/models/user.rb
require 'digest/md5'

class User
  include Mongoid::Document
  include Mongoid::Timestamps
  
  field :login
  field :name
  field :email
  field :session_token
  
  embeds_many :authentications
  
  index ['authentications.provider', 'authentications.uid'], unique: true
  
  validates :login, presence: true, length: { minimum: 2 }, uniqueness: true,
                    format: /^[\w\d\.-]+$/
  validates :email, presence: true, email: true, uniqueness: true
  
  before_create :generate_session_token
  
  def self.build_from_auth(hash, auth)
    User.new do |u|
      u.name  = hash['user_info']['name']
      u.email = hash['user_info']['email']
      u.login = generate_login(u.email, hash['uid'])
      u.authentications = [auth]
    end
  end
  
  def self.generate_login(email, openid)
    login = ''
    login = prefix = loginize(email.sub(/@[^@]+$/, '')) if email
    login = prefix = loginize(openid.gsub(/^https?/, '')) if login.length < 2
    i = 1
    login = prefix + (i += 1).to_s until User.where(login: login).count.zero?
    login
  end
  
  def self.loginize(string)
    string.gsub(/[^\w\d\.-]/, '').downcase
  end
  
  def generate_session_token
    self.session_token = ActiveSupport::SecureRandom.base64(15)
  end
  
  def avatar(size = 50)
    return unless self.email
    'http://gravatar.com/avatar/' +
      Digest::MD5.hexdigest(self.email) + "?s=#{size}&d=identicon"
  end
  
  def name
    super || login
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  protected
  
  def current_user
    @current_user ||= begin
      token = session[:session_token]
      User.where(session_token: token).first if token
    end
  end
  
  def signed_in?
    !!current_user
  end
  
  helper_method :current_user, :signed_in?
  
  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    @auth = Authentication.auth_by_hash(auth_hash)
    @user = @auth.user
    
    if current_user and not @user
      @user = current_user
      @user.authentications << @auth
      flash[:notice] = t.signin.add(@user.login, @auth.provider_name, @auth.uid)
    elsif @user.nil?
      @user = User.build_from_auth(auth_hash, @auth)
      flash[:notice] = t.signin.created(@user.login)
    end
    @user.save!
    session[:session_token] = @user.session_token
  rescue Mongoid::Errors::Validations
    flash[:notice] = nil
    raise unless @user.errors.has_key? :email
    if @user.email.blank?
      flash[:error] = t.signin.empty_email
    else
      occupier = User.where(email: @user.email).first.authentications.first
      flash[:error] = t.signin.occupied_email(@user.email, occupier.provider, 
                                              occupier.provider_name)
    end
  ensure
    redirect_to root_path # TODO. Save path
  end
  
  def destroy
    session.delete :session_token
    redirect_to root_path # TODO. Save path
  end
  
  def failure
    flash[:error] = t.signin.failure[params[:message]]
    redirect_to root_url
  end
  
  private
  
  def auth_hash
    request.env['omniauth.auth'] 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def include_jquery(version)
    javascript_include_tag(Rails.env.production? ?
      "https://ajax.googleapis.com/ajax/libs/jquery/#{version}/jquery.min.js" :
      "lib/development/jquery-#{version}")
  end
  
  def flash_class
    show = flash.reject { |a, b| b.nil? }.to_a
    show.empty? ? {} : { class: show.first.first }
  end
  
  def class_if(cls, check)
    check ? { class: cls } : { }
  end
  
end

app/views/layouts/application.html.haml
!!! 5
%html{ lang: r18n.locale.code }
  %head
    %meta( charset="UTF-8" )
    %title= t.name.title
    = favicon_link_tag
    = csrf_meta_tag
    
    = include_jquery('1.5.1')
    
    = stylesheet_link_tag 'http://fonts.googleapis.com/css?family=Ubuntu'
    = include_stylesheets :application
    = include_javascripts :application
    
  %body
    
    %header{ flash_class }
      .center
        %a.logo( href="/" rel="home" )
          %div
        .bubble
      
      .row
        - flash.each_pair do |type, text|
          - if text
            .flash{ class_if('small', strip_tags(text).length > 115), :class => type }
              .center= text.html_safe
        .top
          .center
            %a.home( href="/" )
              - if signed_in?
                = t.name.with_user(current_user.name)
              - else
                = t.name.header
            - if signed_in?
              - form_tag sessions_path, method: :delete, class: 'exit' do
                %a( href="#" rel="submit" )= t.exit
            - else
              .auth
                %h3= t.signin.title
                %form( action="/auth/open_id" method="get" )
                  .elements
                    %input( type="url" name="openid_url" required )
                    %a( href="#" rel="submit" )
                      .wrap
                        .top
                        .bottom
                        = t.signin.openid_submit
                %a( href="/auth/google" )
                  .wrap
                    .top
                    .bottom
                    Google
                %a( href="/auth/facebook" )
                  .wrap
                    .top
                    .bottom
                    Facebook
                %a( href="/auth/open_id" rel="openid" )
                  .wrap
                    .top
                    .bottom
                    OpenID
    .center
      = yield